---
consequencia_params : {
    'Amputação (exceto dedo)':
        {'dsclesao': ['702070000'],
         'codparteating_not': ['755070000', '757070000'],
         'codcidCategoria': ['S08', 'S18', 'S48', 'S58', 'S68', 'S78', 'S88', 'S98', 'T05'],
         'codcid_not': ['S680', 'S681', 'S981', 'S982'],},

    'Amputação (inclusive dedo)':
        {'dsclesao': ['702070000'],
         'codcidCategoria': ['S08', 'S18', 'S48', 'S58', 'S68', 'S78', 'S88', 'S98', 'T05'],},
    }

...