---
# Conversões (de -> para) de parâmetros descontinuados
CONSEQUENCIA: {'Amputação de membro (exceto dedo)': 'Amputação (exceto dedo)',
               'Amputação de membro (inclusive dedo)': 'Amputação (inclusive dedo)',}
...